sudo: false
language: node_js
node_js:
    - "8"
branches:
    only:
        - master
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - npm run test:coverage -e TRAVIS_NODE_VERSION
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
        branch: master
