sudo: false
language: node_js
node_js:
    - "8"
branches:
    only:
        - master
cache:
    directories:
        - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - npm run test:coverage -e TRAVIS_NODE_VERSION
before_deploy:
    - "npm run build"
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: master
